pro_stage_acceuil:
    path: /pro/stage/acceuil
    controller: App\Controller\ProStageController::index

pro_stage_entreprises:
    path: /pro/stage/entreprises
    controller: App\Controller\ProStageController::entreprises

pro_stage_formations:
    path: /pro/stage/formations
    controller: App\Controller\ProStageController::formations

pro_stage_stage:
    path: /pro/stage/stage/{id}
    controller: App\Controller\ProStageController::stage

pro_stage_afficherStagesParEntreprises:
    path: /pro/stage/afficherStagesParEntreprises/{nom}
    controller: App\Controller\ProStageController::afficherStagesParEntreprises

pro_stage_afficherStagesParFormations:
    path: /pro/stage/afficherStagesParFormations/{intitule}
    controller: App\Controller\ProStageController::afficherStagesParFormations

pro_stage_ajouterEntreprise:
    path: /pro/stage/ajouterEntreprise
    controller: App\Controller\ProStageController::ajouterEntreprise
